RedditClone/config/routes.rb
Rails.application.routes.draw do
  resources :users, only:[:create, :new]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy] do 
    resources :posts, only: [:create, :new]
  end
  resources :posts, except: [:create, :index, :new]
end

RedditClone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RedditClone/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true

  # belongs_to :sub,
  #   primary_key: :id,
  #   foreign_key: :sub_id,
  #   class_name: :Sub

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  has_many :post_subs,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :PostSub,
    inverse_of: :post

  has_many :subs,
    through: :post_subs,
    source: :sub
end

RedditClone/app/models/post_sub.rb
class PostSub < ApplicationRecord
  belongs_to :post,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :Post

  belongs_to :sub,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :Sub
end

RedditClone/app/models/sub.rb
class Sub < ApplicationRecord
  validates :description, :title, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

  # has_many :posts,
  #   primary_key: :id,
  #   foreign_key: :sub_id,
  #   class_name: :Post

  has_many :post_subs,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :PostSub,
    inverse_of: :sub

  has_many :posts,
    through: :post_subs,
    source: :post

end

RedditClone/app/models/user.rb
class User < ApplicationRecord
  validates :username, :session_token, presence:true, uniqueness:true
  validates :password_digest, presence:true
  validates :password, length: {minimum: 6, allow_nil:true}

  after_initialize :ensure_session_token
  
  attr_reader :password

    has_many :subs,
      primary_key: :id,
      foreign_key: :moderator_id,
      class_name: :Sub

    has_many :posts,
      primary_key: :id,
      foreign_key: :author_id,
      class_name: :Post

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    return nil unless user

    user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end
end

RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?
    !!current_user
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

  # def require_logout
  # end
end

RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_login, except: [:show]
  before_action :confirm_author, only: [:edit, :update, :destroy]

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def new
    @subs = Sub.all
    @sub = Sub.find(params[:sub_id])
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @sub = Sub.find(params[:sub_id])
    @post.author_id = current_user.id
    if @post.save
      redirect_to sub_url(@sub)
    else
      @subs = Sub.all
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to sub_url(@post.sub)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end

  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub)
  end

  private
  def post_params
    params.require(:post).permit(:url, :title, :content, sub_ids: [])
  end

  def confirm_author
    @post = Post.find(params[:id])
    if @post.author != current_user
      flash[:errors] = ["Cannot edit post that does not belong to you"]
      redirect_to subs_url 
    end
  end
end

RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user
      login!(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["Invalid Username or Password"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :require_login, only: [:new, :create, :edit, :update]
  before_action :confirm_moderator, only: [:edit, :update]
  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create 
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private
  def confirm_moderator
    @sub = Sub.find(params[:id])
    if @sub.moderator != current_user
      flash[:errors] = ["Cannot edit sub that does not belong to you"]
      redirect_to subs_url 
    end
  end

  def sub_params
    params.require(:sub).permit(:description, :title)
  end
end

RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

RedditClone/app/helpers/application_helper.rb
module ApplicationHelper
end

RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

RedditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

RedditClone/app/helpers/users_helper.rb
module UsersHelper
end

RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |err| %>
          <li><%= err %></li>
        <% end %>
      </ul>
    <% end %>
    
    <% if logged_in? %>
      <%= current_user.username %>

      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Sign Out">
      </form>
      
    <% end %>

    <%= yield %>
  </body>
</html>

RedditClone/app/views/posts/edit.html.erb
<h2>Edit Post for
  <%= @post.title %>
</h2>

<form action="<%= post_url(@post)%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">

  <label>
    Title:
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <br>
  <br>

  <label>
    URL (optional):
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <br>
  <br>

  <label>
    Content (optional):
    <textarea name="post[content]"><%= @post.content %></textarea>
  </label>

  <br>
  <br>

  <input type="submit" value="Update Post">

</form>

RedditClone/app/views/posts/new.html.erb
<h2>New Post for <%= @sub.title %></h2>

<form action="<%= sub_posts_url(@sub)%>" method="post" >
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label>
    Title: 
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <br>
  <br>

  <label>
    URL (optional): 
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <br>
  <br>

  <label>
    Content (optional): 
    <!-- <input type="text" name="post[content]" value="<%= @post.content %>"> -->
    <textarea name="post[content]"><%= @post.content %></textarea>
  </label>
  
  <br>
  <br>

  <% @subs.each do |sub| %>
    <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"><%= sub.title %><br>
  <% end %>

  <br>
  <br>

  <input type="submit" value="Create New Post">

</form>

RedditClone/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>


Post Author: <%= @post.author.username %>
<br>
URL: <%= @post.url %>
<br>
Post Content: <%= @post.content %>

<br>
<br>

<a href="<%= edit_post_url(@post) %>">Edit Post</a>

<br>

<form action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">

  <input type="submit" value="Remove Post">

</form>

RedditClone/app/views/subs/edit.html.erb
<h2>Edit Sub</h2>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">
  
  <label>
    Title
    <input type='text' name='sub[title]' value='<%= @sub.title %>'>
  </label>


  <label>
    Description
    <input type='text' name='sub[description]' value='<%= @sub.description %>'>
  </label>

  <input type='submit' value='Edit Sub'>
</form>

RedditClone/app/views/subs/index.html.erb
<h2>This is the Sub Index</h2>
<ul>
  <% @subs.each do |sub| %>
    <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
  <% end %>
</ul>

RedditClone/app/views/subs/new.html.erb
<h2>New Sub</h2>

<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Title
    <input type='text' name='sub[title]' value='<%= @sub.title %>'>
  </label>


  <label>
    Description
    <input type='text' name='sub[description]' value='<%= @sub.description %>'>
  </label>

  <input type='submit' value='Create New Sub'>
</form>

RedditClone/app/views/subs/show.html.erb
<h2><%= @sub.title %></h2>

<%= @sub.description %>
<br>
<a href='<%= edit_sub_url(@sub) %>'>Edit Sub</a>

<h2>Posts</h2>
<ul>
  <% @sub.posts.each do |post| %>
    <li><a href='<%= post_url(post) %>'><%= post.title %></a></li>
  <% end %>
</ul>

<a href='<%= new_sub_post_url(@sub) %>'>Add Post</a>

RedditClone/app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Username
    <input type="text" name="user[username]">
  </label>

  <label>
    Password
    <input type="password" name="user[password]">
  </label>

  <input type="submit" value="Sign Up">

</form>